site_name: KU Genomic Data Science Core
site_url: https://KU-GDSC.github.io/
repo_url: https://github.com/KU-GDSC/ku-gdsc.github.io/
repo_name: 'KU-GDSC/ku-gdsc.github.io'


theme:
    name: material
    palette:
      scheme: slate
    icon:
      repo: fontawesome/brands/github

    features:
      - navigation.path
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.indexes
      - navigation.top
      - toc.integrate
      - toc.follow

markdown_extensions:
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: "#"

plugins:
  - search
  - git-revision-date-localized:
      type: date
      enabled_creation_date: true

nav:
    - index.md
    - people.md
    - policies.md
    - services.md
    - Documentation and Training:
      - documentation/index.md
      - documentation/quick_starts.md
      - documentation/slow_starts.md
      - documentation/cheatsheet.md
