site_name: KU Genomic Data Science Core
site_url: https://KU-GDSC.github.io/
theme:
    name: material
    palette:
      - scheme: slate

    features:
      - navigation.path
        
markdown_extensions:
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: "#"
